### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by seanfilidis** [jesseward/plex-lastfm-scrobbler#16]
On Windows the installation procedure seemed to work, but I get the following errors when I try to run the application:

![11d0062a-4716-11e4-82d5-04cf7f37f188](https://cloud.githubusercontent.com/assets/8947739/4434506/a6f70f5c-4719-11e4-98e2-7a52f24848a3.PNG)

My config file looks like: 

![capture](https://cloud.githubusercontent.com/assets/8947739/4434437/b4c22fb6-4716-11e4-9f88-69a6e70ea1dd.PNG)

Would love to get this working...

**Comment by seanfilidis** [comment]
Update... I have since upgraded to a new machine with Windows 8.1 on it. Everything works smoothly except, just like on the last machine, it simply stops scrobbling after a while of playing music, for no apparent reason. It does not have to do with putting the computer to sleep as I previously though (I know this because I never put this computer to sleep). The script simply stops working after a while, even through it still seems to be running in the command window. The only way to make it start scrobbling is to restart the machine. Right now I am looking at my last.fm profile, and it seems to have stopped scrobbling half way through a Van Morrison album yesterday. Nothing has scrobbled since then, even though I have played lots of music in the meantime. It seems totally random.

**Comment by rwa66** [comment]
I am experiencing the same problem on my Windows 2008R2 Server. 
Out of the blue Plex Lastfm Scrobbler stops scrobbling. The only thing that gets it going is a complete restart of the machine.
It looks like it happens at random. No album change, no exotic characters, nothing i can think of.
I can share the log files, but I am afraid they don't give much more info then earlier posted logs.
If I can help squash this one, please let me know. 
I would kill for a stable scrobbler for Plex on Windows. ;)

**Comment by seanfilidis** [comment]
I give up. It almost never works. Only for a little bit after restarting the machine. =(

**Comment by jesseward** [comment]
@seanfilidis thanks for you efforts. I will update the README with more verbiage surrounding support for windows. Unfortunately i do not have a windows based development machine, and don't have enough drive at the moment to hunt one down and focus testing on Windows.

If a windows developer wants to pick this up, please do feel free, pull requests are welcomed.
