### ISSUE TITLE
Error 403: Unable to submit query to last.fm

### ISSUE THREAD

**Issue by avinash** [jesseward/plex-lastfm-scrobbler#40]
Hi,

plex-lastfm-scrobbler was working great until a few days ago. I now keep getting errors such as:

[plex_scrobble.lastfm _do_raw_lastfm_query] [ERROR] Unable to submit query http://ws.audioscrobbler.com/2.0/?api_sig=[REMOVED FOR CLARITY]&token=[REMOVED FOR CLARITY]&api_key=[REMOVED FOR CLARITY]&method=auth.getSession - HTTP Error 403: Forbidden

and

Unable to submit post data http://ws.audioscrobbler.com/2.0/ - HTTP Error 403: Forbidden

I've deleted the session_key file but I have noticed that plex-scrobbler.py cannot re-create it even though I successfully authenticated the app on the Last.fm website and answered Y to the script.

Has Last.fm just changed auth.getSession?

Are other people getting the same kind of issue?

Thanks,
Avinash

**Comment by avinash** [comment]
I've just noticed the following on status.last.fm:

We are currently experiencing difficulties and as such you may find recently submitted scrobbles are not being displayed on the website. We apologise for any inconvenience and our engineers are working on this. Posted about 6 days ago by jon

Are the two related?

**Comment by jesseward** [comment]
hey @avinash thanks for reporting. Will take a look this weekend and update this ticket
