### ISSUE TITLE
Add hint to README that Plex supports Last.FM scrobbling

### ISSUE THREAD

**Issue by sensebat** [jesseward/plex-lastfm-scrobbler#46]
https://www.plex.tv/blog/plex-media-server-v0-9-12-5-a-tasty-update/

You can just configure your Plex account to automatically scrobble everything to Last.FM. The Readme should recognize that. It should introduce everything with a use case for this addon, why and when you would use it.

It seems to me (though I might be wrong) that the only use case for this would be to scrobble multiple users to the same Last.FM account to get recommendations etc. for an entire Plex Media Server, rather than for an individual user's tastes.

It's pretty rough (and admittedly not your job) to document Plex's Last.FM support. It would still improve both Plex, the user's experience trying to achieve this and this project's documentation if there was a note explaining how this differs from Plex's built-in functionality.

**Comment by yacn** [comment]
Woah, thanks for the heads up. I had no idea Plex added scrobbling support. As a current Windows PMS user I was about to dive into trying to set this up on Windows Server since it seems to only be tested/confirmed working on Linux -- now there's no need. Thanks!

**Comment by jesseward** [comment]
@sensebat : Thanks a lot. I have updated the README to reflect their addition of this feature.  Note that I have not used Plex for a few years now so if my wording is not appropriate, please feel free to log a PR against the README and I will merge.
